# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_auto_20161201_1606'),
        ('loja', '0010_auto_20161119_2248'),
    ]

    operations = [
    ]
