# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_auto_20161214_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(height_field=172, upload_to='loja/static/product_images', width_field=170),
        ),
    ]
